name: 'Add PR to Project Board - Wallet Framework Team'

on:
  workflow_dispatch:
  pull_request:
    types: [opened, labeled, review_requested]

# Add these permissions
permissions:
  repository-projects: write
  pull-requests: write

jobs:
  add-to-project:
    name: Add PR to Project Board
    runs-on: ubuntu-latest
    env:
      TEAM_NAME: 'wallet-framework-engineers'
      TEAM_LABEL: 'team-wallet-framework'

    steps:
      # Test default token access
      - name: Check GITHUB_TOKEN
        run: |
          if [ -n "${{ secrets.GITHUB_TOKEN }}" ]; then
            echo "Default GITHUB_TOKEN is set"
          else
            echo "Default GITHUB_TOKEN is not set"
          fi

      # Test custom token access
      - name: Check custom token
        run: |
          if [ -n "${{ secrets.CORE_ADD_PRS_TO_PROJECT_TEST }}" ]; then
            echo "CORE_ADD_PRS_TO_PROJECT_TEST is set"
          else
            echo "CORE_ADD_PRS_TO_PROJECT_TEST is not set"
          fi
          
      # List available secret names (will not show values)
      - name: Debug available secrets
        run: |
          echo "Available secret names:"
          echo "${{ toJSON(secrets) }}" | jq 'keys'
          
      - name: Add PR to project board
        uses: actions/add-to-project@v1.0.1
        if: |
          github.event.requested_team.name == env.TEAM_NAME || 
          contains(github.event.pull_request.labels.*.name, env.TEAM_LABEL)
        with:
          project-url: https://github.com/users/desi/projects/1
          github-token: ${{ secrets.CORE_ADD_PRS_TO_PROJECT_TEST }}
